Importing libraries

In [9]:
import numpy as np

Initializing variables

In [10]:
nParticles = 10
vmin = -2
vmax = 2
vx = np.random.uniform(vmin, vmax, nParticles)
vy = np.random.uniform(vmin, vmax, nParticles)
t = 1

vx, vy

(array([ 0.06195238,  0.57652805, -0.42904105, -1.3351336 ,  0.55252517,
        -1.63351554, -1.52563906,  0.00670221,  1.83400082,  1.77929145]),
 array([ 1.28943651, -0.18923887,  1.3132125 , -0.33628481,  1.12270734,
        -1.08351512, -0.40367405,  1.30817598,  0.0429682 ,  1.47257197]))

Defining the function $f(x,y)=(1-x)^2+100(y-x^2)^2$

In [11]:
def f(x, y):
    x = int(x)
    y = int(y)
    return (1-x)**2 + 100*(y-(x**2))**2

Initializing 21 pair random particles betwen the range -5, 5

In [12]:
positions = np.random.uniform(-5, 5, ((nParticles, 2)))
positions

array([[ 4.29234561,  3.58197269],
       [-0.50363317,  4.58650945],
       [ 2.09868071, -0.04299002],
       [-1.58186453, -4.4628762 ],
       [-0.58606423, -1.14709036],
       [-4.5024357 ,  4.98661842],
       [ 1.78382206,  4.97055867],
       [ 0.53728651, -2.9004757 ],
       [-2.64971592, -2.92965422],
       [-3.4165336 , -4.83138989]])

In [13]:
bestPos = positions #making the pre-loop best individual positions same as positions

In [14]:
max_it = 1000 #Initializing the max number of iterations

Main loop

In [15]:
evalPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(nParticles)]) #gettig the pre-loop particles performances
print(evalPos, np.mean(evalPos), t)

fResult = []

while t<max_it:

    fi1 = np.random.uniform(0, 2.05, nParticles) #generating the fi1 random values vector
    fi2 = np.random.uniform(0, 2.05, nParticles) #generating the fi2 random values vector

    for particle in range(nParticles): #for each particle

        evalPos = f(positions[particle, 0], positions[particle, 1]) #getting each particle performance
        evalBestPos = f(bestPos[particle, 0], bestPos[particle, 1]) #getting each best particle performance

        if evalPos < evalBestPos: #if position performance is better than their best performance 
            bestPos[particle] = positions[particle] #update best position

        bestNeigIndx = particle #make current particle the best neighbour
        neigIndices = [particle-1, particle+1] #getting neighbours indices

        for neighbour in range(len(neigIndices)): #for each neighbour

            neigPos = np.take(bestPos, neigIndices[neighbour], mode='wrap', axis=0) #take neighbours best positions
            evalBestNeigPos = f(neigPos[0], neigPos[1]) #getting each best neighbour performance
            evalBestGerPos = f(positions[bestNeigIndx, 0], positions[bestNeigIndx, 1]) #getting best general performance

            if evalBestNeigPos < evalBestGerPos: #if best neighbour performance is better than best general performance
                
                if neigIndices[neighbour] == nParticles: #avoid unbounds
                    bestNeigIndx = 0
                else:
                    bestNeigIndx = neigIndices[neighbour] #update best neighbour index

        vx[particle] = vx[particle] + fi1[particle] * (bestPos[particle, 0]-positions[particle, 0]) \
                        + fi2[particle] * (bestPos[bestNeigIndx, 0]-positions[particle, 0]) #updating velocity

        if vx[particle] > vmax: #limitating max velocity
            vx[particle] = vmax

        if vx[particle] < vmin: #limitating min velocity
            vx[particle] = vmin

        positions[particle, 0] = positions[particle, 0] + vx[particle] #updating x coordinate
        positions[particle, 1] = positions[particle, 1] + vx[particle] #updating y coordinate

    evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))])
    fResult.append(np.mean(evalIndPos)) #appending each iteration mean performance 

    t+=1

print(np.min(fResult))

[16909  1601  1601  2504   101 14425   900   401  3609 16916] 5896.7 1
272.5


In [16]:
print(positions[0])
print(f(0.0089, 0.0079))

[5.05131267 4.34093975]
1
