Importing libraries

In [1]:
import numpy as np

Initializing variables

In [2]:
nParticles = 10
vmin = -2
vmax = 2
vx = np.random.uniform(vmin, vmax, nParticles)
vy = np.random.uniform(vmin, vmax, nParticles)
t = 1

vx, vy

(array([ 1.46424998,  1.00679379, -0.99494425,  1.59198952, -1.01761563,
        -0.26537793,  1.8381176 ,  0.73417017,  1.44142122,  1.38589221]),
 array([ 1.9096603 , -0.4056354 , -1.55850897,  0.73661991, -1.93363758,
        -0.16997944, -1.07879989, -0.99415843, -0.29923336, -0.41297684]))

Defining the function $f(x,y)=(1-x)^2+100(y-x^2)^2$

In [3]:
def f(x, y):
    x = int(x)
    y = int(y)
    return (1-x)**2 + 100*(y-(x**2))**2

Initializing 21 pair random particles betwen the range -5, 5

In [4]:
positions = np.random.uniform(-5, 5, ((nParticles, 2)))
positions

array([[-1.30566707, -0.89286303],
       [-2.50075481,  1.59248652],
       [-0.97543072,  3.75674252],
       [ 0.68220456, -1.8511845 ],
       [-0.42205381,  3.21435969],
       [-2.95975105,  1.59264092],
       [ 1.61032609,  2.95461991],
       [-1.04037919,  4.13098046],
       [ 0.79646464, -3.70300513],
       [ 2.16081304,  0.24101295]])

In [5]:
bestPos = positions #making the pre-loop best individual positions same as positions

In [6]:
max_it = 1000 #Initializing the max number of iterations

Main loop

In [7]:
evalPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(nParticles)]) #gettig the pre-loop particles performances
print(evalPos, np.mean(evalPos), t)

fResult = []

while t<max_it:

    fi1 = np.random.uniform(0, 2.05, nParticles) #generating the fi1 random values vector
    fi2 = np.random.uniform(0, 2.05, nParticles) #generating the fi2 random values vector

    for particle in range(nParticles): #for each particle

        evalPos = f(positions[particle, 0], positions[particle, 1]) #getting each particle performance
        evalBestPos = f(bestPos[particle, 0], bestPos[particle, 1]) #getting each best particle performance

        if evalPos < evalBestPos: #if position performance is better than their best performance 
            bestPos[particle] = positions[particle] #update best position

        bestNeigIndx = particle #make current particle the best neighbour
        neigIndices = [particle-1, particle+1] #getting neighbours indices

        for neighbour in range(len(neigIndices)): #for each neighbour

            neigPos = np.take(bestPos, neigIndices[neighbour], mode='wrap', axis=0) #take neighbours best positions
            evalBestNeigPos = f(neigPos[0], neigPos[1]) #getting each best neighbour performance
            evalBestGerPos = f(positions[bestNeigIndx, 0], positions[bestNeigIndx, 1]) #getting best general performance

            if evalBestNeigPos < evalBestGerPos: #if best neighbour performance is better than best general performance
                
                if neigIndices[neighbour] == nParticles: #avoid unbounds
                    bestNeigIndx = 0
                else:
                    bestNeigIndx = neigIndices[neighbour] #update best neighbour index

        vx[particle] = vx[particle] + fi1[particle] * (bestPos[particle, 0]-positions[particle, 0]) \
                        + fi2[particle] * (bestPos[bestNeigIndx, 0]-positions[particle, 0]) #updating velocity

        if vx[particle] > vmax: #limitating max velocity
            vx[particle] = vmax

        if vx[particle] < vmin: #limitating min velocity
            vx[particle] = vmin

        positions[particle, 0] = positions[particle, 0] + vx[particle] #updating x coordinate
        positions[particle, 1] = positions[particle, 1] + vx[particle] #updating y coordinate

    evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))])
    fResult.append(np.mean(evalIndPos))

    t+=1

print(np.min(fResult))

[ 104  909  901  101  901  909  100  904  901 1601] 733.1 1
411.6


In [8]:
print(positions[0])
print(f(0.0089, 0.0079))

[2.40581903 2.81862307]
1
