Importing libraries

In [763]:
import numpy as np

In [764]:
nParticles = 10
vmin = -2
vmax = 2
vx = np.random.uniform(vmin, vmax, nParticles)
vy = np.random.uniform(vmin, vmax, nParticles)
t = 1

vx, vy

(array([-0.59921187,  0.00528626,  1.88165688, -1.16652471,  0.01223517,
         0.18245022, -0.43715333, -1.87905199,  1.15018183,  1.96879666]),
 array([-0.90550952, -1.20756116,  0.41400905, -1.074693  ,  0.26620369,
        -1.74711355, -1.78837263, -1.71867941, -0.74677687,  0.04917606]))

Defining the function $f(x,y)=(1-x)^2+100(y-x^2)^2$

In [765]:
def f(x, y):
    x = int(x)
    y = int(y)
    return (1-x)**2 + 100*(y-(x**2))**2

Initializing 21 pair random particles betwen the range -5, 5

In [766]:
positions = np.random.uniform(-5, 5, ((nParticles, 2)))
positions

array([[-3.53687624,  1.57975026],
       [-2.07381196,  1.58486415],
       [ 3.49077602, -4.4797038 ],
       [-0.03290172,  4.98784061],
       [ 2.19072632, -2.57378777],
       [ 3.28977054, -4.63147176],
       [ 1.61421112,  0.77897201],
       [-0.224267  , -4.91164826],
       [-4.61311079,  2.30046998],
       [ 4.38688255, -3.09857134]])

In [767]:
bestIndPos = positions #gettig the pre-loop best individual positions

In [768]:
evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(nParticles)]) #gettig the pre-loop individual performances
evalIndPos

array([ 6416,   909, 16904,  1601,  3601, 16904,   100,  1601, 19625,
       36109])

Getting the best individual performance

In [769]:
max_it = 1000

In [770]:
evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))])
print(evalIndPos, np.mean(evalIndPos), t)

bResult = []

while t<max_it:

    fi1 = np.random.uniform(0, 2.05, nParticles) #generating the fi1 random values vector
    fi2 = np.random.uniform(0, 2.05, nParticles) #generating the fi2 random values vector

    for particle in range(nParticles): #for each particle

        evalPos = f(positions[particle, 0], positions[particle, 1]) #getting each individual position performance
        evalBestIndPos = f(bestIndPos[particle, 0], bestIndPos[particle, 1]) #getting each best individual position performance

        if evalPos < evalBestIndPos: #if current individual performance is better than their best performance 
            bestIndPos[particle] = positions[particle] #update best individual performance

        bestNeigIndx = particle #make current particle the best neighbour

        neigIndices = [particle-1, particle+1] #getting particle neighbours indices

        for neighbour in range(len(neigIndices)):
            neigPos = np.take(bestIndPos, neigIndices[neighbour], mode='wrap', axis=0)
            evalBestNeigPos = f(neigPos[0], neigPos[1])
            evalBestGerPos = f(positions[bestNeigIndx, 0], positions[bestNeigIndx, 1])

            if evalBestNeigPos < evalBestGerPos: #comparing current particle performance to current neighbour
                
                if neigIndices[neighbour] == nParticles:
                    bestNeigIndx = 0
                else:
                    bestNeigIndx = neigIndices[neighbour] #bestNeigPos updated if current neighbour is better than current particle

        vx[particle] = vx[particle] + fi1[particle] * (bestIndPos[particle, 0]-positions[particle, 0]) + fi2[particle] * (bestIndPos[bestNeigIndx, 0]-positions[particle, 0])

        if vx[particle] > vmax:
            vx[particle] = vmax

        if vx[particle] < vmin:
            vx[particle] = vmin

        positions[particle, 0] = positions[particle, 0] + vx[particle]

        #vy[particle] = vy[particle] + fi1[particle] * (bestIndPos[particle, 1]-positions[particle, 1]) + fi2[particle] * (bestIndPos[bestNeigIndx, 1]-positions[particle, 1])

        #if vy[particle] > vmax:
            #vy[particle] = vmax

        #if vy[particle] < vmin:
            #vy[particle] = vmin

        positions[particle, 1] = positions[particle, 1] + vx[particle]

    evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))])

    bResult.append(np.mean(evalIndPos))

    t+=1

    #print(evalIndPos, np.mean(evalIndPos), t)

print(np.min(bResult))

#positions

[ 6416   909 16904  1601  3601 16904   100  1601 19625 36109] 10377.0 1
2551.9


In [771]:
#evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))])
#evalIndPos

In [772]:
print(positions[0])
print(f(0.0089, 0.0079))

[-0.09515499  5.02147151]
1
