Importing libraries

In [134]:
import numpy as np

In [135]:
vmin = -2
vmax = 2
vx = np.random.uniform(vmin, vmax, 21)
vy = np.random.uniform(vmin, vmax, 21)
t = 1
max_it = 5

vx, vy

(array([-1.84262285,  0.20715066, -0.46164835, -0.51183703, -0.81004843,
         0.41830366, -1.7119201 , -1.41647865, -1.27195363,  1.87390244,
         1.92051504, -1.39955598, -0.52662777, -0.23731582,  0.73161508,
         1.24598598, -1.29471929,  1.66454723, -1.33446242,  0.75321592,
         0.6092031 ]),
 array([-0.48009082,  1.15915466, -1.12088652,  1.02258748, -0.88029922,
         1.58479046, -0.97952899,  0.62967181, -1.45851414,  0.29909023,
         0.70964054, -0.04960445,  0.45443071,  0.9019233 ,  1.16596962,
        -0.53326399, -1.52998191,  1.13301791, -0.49089138,  0.45219249,
        -1.54720213]))

Defining the function $f(x,y)=(1-x)^2+100(y-x^2)^2$

In [136]:
def f(x, y):
    return (1-x)**2 + 100*(y-(x**2))**2

Initializing 21 pair random particles betwen the range -5, 5

In [137]:
positions = np.random.uniform(-5, 5, ((21, 2)))
positions

array([[ 0.18940156,  4.06830273],
       [-1.61851822, -0.50726993],
       [-4.40757857,  1.94538695],
       [-0.35992807, -3.16129077],
       [ 0.83961886, -1.43367378],
       [-4.35681885, -2.75947505],
       [-1.16465339, -0.70207089],
       [-3.60555683,  1.18630196],
       [ 0.86658743, -4.55483206],
       [ 4.58137973,  2.44315901],
       [ 2.77112994,  2.49980585],
       [ 4.60456346, -0.79551907],
       [ 3.13228879,  4.84445278],
       [ 3.19185385,  2.72084225],
       [ 1.00552078,  1.16149023],
       [ 2.08934262,  1.86368042],
       [-2.25799455,  4.68411318],
       [ 1.57972337, -3.8101908 ],
       [-3.18262557, -0.85513965],
       [-2.5968547 , -0.03150483],
       [ 1.91796729,  2.47217076]])

In [138]:
bestIndPos = positions #gettig the pre-loop best individual positions

In [139]:
evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))]) #gettig the pre-loop individual performances
evalIndPos

array([ 1626,   984, 30589,  1084,   457, 47297,   428, 13977,  2815,
       34407,  2685, 48402,  2471,  5580,     2,   627,    27,  3976,
       12082,  4603,   146])

Getting the best individual performance

In [140]:
while t<max_it:

    for particle in range(len(positions)): #for each particle

        fi1 = np.random.uniform(0, 2.05, 21) #generating the fi1 random values vector
        fi2 = np.random.uniform(0, 2.05, 21) #generating the fi2 random values vector

        evalPos = f(positions[particle, 0], positions[particle, 1]) #getting each individual position performance
        evalBestIndPos = f(bestIndPos[particle, 0], bestIndPos[particle, 1])

        if evalPos < evalBestIndPos: #if current individual performance is better than their best performance 
            bestIndPos[particle] = positions[particle] #update best individual performance

        bestNeigIndx = particle #make current particle the best neighbour

        neigIndices = [particle-1, particle+1] #getting particle neighbours indices

        for neighbour in range(2):
            neigPos = np.take(bestIndPos, neigIndices[neighbour], mode='wrap', axis=0)
            evalBestNeigPos = f(neigPos[0], neigPos[1])

            if evalBestNeigPos < evalPos: #comparing current particle performance to current neighbour
                
                bestNeigIndx = neigIndices[neighbour] #bestNeigPos updated if current neighbour is better than current particle

                if neigIndices[neighbour] == 21:
                    bestNeigIndx = 0

        vx[particle] = vx[particle] + fi1[particle] * (bestIndPos[particle, 0]-positions[particle, 0]) 
        + fi2[particle] * (bestIndPos[bestNeigIndx, 0]-positions[particle, 0])

        if vx[particle] > vmax:
            vx[particle] = vmax

        if vx[particle] < vmin:
            vx[particle] = vmin

        positions[particle, 0] = positions[particle, 0] + vx[particle]

        vy[particle] = vy[particle] + fi1[particle] * (bestIndPos[particle, 1]-positions[particle, 1]) 
        + fi2[particle] * (bestIndPos[bestNeigIndx, 1]-positions[particle, 1])

        if vy[particle] > vmax:
            vy[particle] = vmax

        if vy[particle] < vmin:
            vy[particle] = vmin

        positions[particle, 1] = positions[particle, 1] + vx[particle]

        t+=1

positions

array([[-1.65322129,  2.22567988],
       [-1.41136756, -0.30011927],
       [-4.86922693,  1.4837386 ],
       [-0.8717651 , -3.6731278 ],
       [ 0.02957043, -2.24372221],
       [-3.93851519, -2.34117139],
       [-2.87657348, -2.41399099],
       [-5.02203549, -0.2301767 ],
       [-0.4053662 , -5.82678569],
       [ 6.45528217,  4.31706145],
       [ 4.69164497,  4.42032089],
       [ 3.20500748, -2.19507505],
       [ 2.60566102,  4.31782501],
       [ 2.95453803,  2.48352643],
       [ 1.73713586,  1.89310532],
       [ 3.33532859,  3.1096664 ],
       [-3.55271384,  3.38939389],
       [ 3.2442706 , -2.14564357],
       [-4.51708799, -2.18960207],
       [-1.84363878,  0.72171109],
       [ 2.52717039,  3.08137386]])

In [141]:
evalIndPos = np.array([int(f(positions[particle, 0], positions[particle, 1])) for particle in range(len(positions))])
evalIndPos

array([    32,    531,  49432,   1968,    504,  31897,  11439,  64811,
         3591, 139558,  30958,  15547,    613,   3904,    127,   6429,
         8544,  16060,  51077,    724,   1094])

In [142]:
print(f(1, 1))

0
